### ISSUE TITLE
Fix overlapping issue on /about/who-we-are

### ISSUE THREAD

**Issue by lieseld** [czqoocavatsim/czqo-core#103]
https://streamable.com/w9jcdg and https://cdn.discordapp.com/attachments/736558901515911189/770083569540268042/unknown.png

**Comment by viljowilding** [comment]
![image](https://user-images.githubusercontent.com/31629281/97123412-a9808b00-1723-11eb-8e93-802bbb6fae22.png)

looks like the container is on top of the menu

**Comment by viljowilding** [comment]
dbf710cdc9325a456bb58babbfba02f192d3d724

well, I will find time for the navbar, but in the meantime this should fix it

**Comment by viljowilding** [comment]
![image](https://i.imgur.com/RfcZpYj.png)

Never mind - I thought I'd fixed this, but clearly not. Best solution might just be redesigning the jarallax element.

**Comment by cocoiadrop** [comment]
Did a temporary fix for mobile but yeah best redesign: https://gyazo.com/5e444c84852244faea164921accb3e7d

**Comment by cocoiadrop** [comment]
@viljowilding Idea - use the header code for other pages (see /roster) for example to redo the element

```
@extends('layouts.master', ['solidNavBar' => false])
@section('title', 'Policies - ')
@section('description', 'Policies and guidelines for operations in Gander Oceanic')

@section('content')
    <div class="card card-image blue rounded-0">
        <div class="text-white text-left pb-2 pt-5 px-4">
            <div class="container">
                <div class="py-5">
                    <h1 class="font-weight-bold" style="font-size: 3em;">Policies</h1>
                    <p style="font-size: 1.2em;" class="mt-3 mb-0">
                        Policies and guidelines for operations in Gander Oceanic. These policies may be updated from time to time.
                    </p>
                </div>
            </div>
        </div>
    </div>
```

**Comment by cocoiadrop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Overlapping issue on "who are we" page](https://trello.com/c/wXzdkVJK/8-overlapping-issue-on-who-are-we-page)
