### ISSUE TITLE
Redesign navigation bar

### ISSUE THREAD

**Issue by lieseld** [czqoocavatsim/czqo-core#104]
- Move away from stock Bootstrap as it isn't customisable to our needs
- Better responsiveness on < md screens
- Less "corporate" and more friendly

@viljowilding has thoughts that he will comment when he is ready to

There is also Elliot's design for VATPAC we can look at

**Comment by cocoiadrop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User interface overhaul](https://trello.com/c/XxCzAqPY/7-user-interface-overhaul)
