### ISSUE TITLE
Drop down menu colours

### ISSUE THREAD

**Issue by cocoiadrop** [czqoocavatsim/czqo-core#110]
Subject: Drop down menu colours.

Content: Hello, i noticed if something isn't selected in dropdown menu its colour is more towards grey which blends with white and its hard to see what is written obviously you could select that option then the colour is more explicts

**Comment by viljowilding** [comment]
Will prioritise this, I do love CSS

**Comment by cocoiadrop** [comment]
Example of what they're talking about: https://cdn.discordapp.com/attachments/729597611111088210/777744208538370058/asdsadasdsad.png

It's to do with dark mode.
