### ISSUE TITLE
Bug report: https://ganderoceanic.com/about/staff

### ISSUE THREAD

**Issue by lieseld** [czqoocavatsim/czqo-core#113]
## URL:
https://ganderoceanic.com/about/staff
## Describe the issue:
Profile Pictures became squished together...sometimes all the profile pictures other times some of the profile pictures and other times doesn't work at all, sent pictures to you on discord for reference

**Comment by cocoiadrop** [comment]
https://cdn.discordapp.com/attachments/762899683748085770/777449831648067604/unknown.png

**Comment by viljowilding** [comment]
![image](https://user-images.githubusercontent.com/31629281/99407396-f3096380-28e6-11eb-9288-39ae8323ddb7.png)

I've not been able to find this bug (more screenshots please!), however I've made the staff cards the same height as their siblings and set the ZQO1 card to full width so Rudi can be added and not leave an empty space.

**Comment by cocoiadrop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Staff page avatars](https://trello.com/c/TdpLIsVh/6-staff-page-avatars)
