### ISSUE TITLE
Pilot booking system

### ISSUE THREAD

**Issue by lieseld** [czqoocavatsim/czqo-core#114]
Andrew has requested a booking system for pilots in a real-ops type event, like Perth Real Ops or whatever. Example: https://booking.vatpac.org/

Requirements

- Allow for insertation (That's a word.)  of slots/flights by staff either manually or via a CSV/JSON file.
- Allow for booking by pilots. 
- Allow for delivery of notifications such as routes etc by staff
- I'm sure we'll think of more

@andrewogden1678 if you want to add anything

**Comment by cocoiadrop** [comment]
https://github.com/czqoocavatsim/pilot-booking
