### ISSUE TITLE
Email when solo certification ends

### ISSUE THREAD

**Issue by viljowilding** [czqoocavatsim/czqo-core#118]
Send an automatic warning email to ZQO3 and ZQO13 when a controller's solo certification is about to expire.

Should be a simple enough scheduled task, think I'll do this myself.

**Comment by cocoiadrop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Email when student's solo certification ends](https://trello.com/c/Ev3Iwdtz/4-email-when-students-solo-certification-ends)
