### ISSUE TITLE
Documents/Positions pages

### ISSUE THREAD

**Issue by lieseld** [czqoocavatsim/czqo-core#167]

**Comment by dsolesvik** [comment]
Could you give a basic idea of what is needed here?

**Comment by lieseld** [comment]
> Could you give a basic idea of what is needed here?

Positions page would be a listen of our controller positions + callsign + freq (I've done the gander radio set already)

Documents is what ATC resources is now

**Comment by dsolesvik** [comment]
> > Could you give a basic idea of what is needed here?
> 
> Positions page would be a listen of our controller positions + callsign + freq (I've done the gander radio set already)
> 
> Documents is what ATC resources is now

Thanks Under what czqo-core file do these fall under, so I can push my commits into that file?

**Comment by lieseld** [comment]
@dsolesvik It is all in resources/views/operations and always on the 2.0 branch. The files there are setup with sample documents and that Gander Radio positions (Delivery + Shanwick Rad/Del to go) so you can see how it works

**Comment by dsolesvik** [comment]
https://github.com/czqoocavatsim/czqo-core/commit/9ab6e0d507f685a664d0d0d27853baa75459057a
https://github.com/czqoocavatsim/czqo-core/commit/ecff054cd2e1ff67fa921a9d7fb9bcbb11b161bf
