### ISSUE TITLE
Network Statistics Page

### ISSUE THREAD

**Issue by andrewogden1678** [czqoocavatsim/czqo-core#35]
### Functional Requirements
*Meaning of **timeframes**: one week (daily statistics), 28 days (7 day statistics) and activity cycle (monthly numbers*

**Monitored Positions:**
- [ ] Can list all currently monitored positions
- [ ] Can select a monitored position
- [ ] Can show hours logged on a monitored position over all the timeframes
- [ ] Can show number of sessions logged for a position over all the timeframes
- [ ] Can show a togglable graph for number of sessions over all the timeframes
- [ ] Can show a togglable graph for hours logged over all the timeframes (maybe have one graph area, but have a tab to switch between both)

**Controller Activity:**
- [ ] Controllers can view their own hours logged on all positions over all the timeframes
- [ ] Controllers can select an individual position and view own hours logged over all the timeframes
- [ ] Controllers can view their own number of sessions logged on all positions over all the timeframes
- [ ] Controllers can select an individual position and view own number of sessions logged over all the timeframes
- [ ] Controllers can view togglable graphs to display the above data (one graph, tabs to switch is my idea but I'll leave it up to choice)
- [ ] Controllers can view all their past (historical) sessions for all positions, and for individual positions
- [ ] STAFF (>level 2 permissions) can view their own data and can also search individual users to display all the above data

**Overall Statistics:**
- [ ] Can show total number of sessions logged on Oceanic over all the timeframes
- [ ] Can show total hours logged on Oceanic over all the timeframes
- [ ] Can show uptime as a percentage over all the timeframes (filter by Gander, Shanwick and All)
- [ ] Can show graphs for the above data (same suggestion as mentioned for previous graphs)

**Comment by lieseldownes24** [comment]
Moving to 1.8.0 milestone but may be in a 1.7.x release

**Comment by cocoiadrop** [comment]
Perhaps me and Josh can finish backend for this while Viljo does UI? Let's finally get it done lol
