### ISSUE TITLE
Website vatviewer

### ISSUE THREAD

**Issue by andrewogden1678** [czqoocavatsim/czqo-core#74]
### Functional Requirements
- [x] Display aircraft and their callsigns
- [ ] Display current NAT Tracks, their letter, and waypoint information
- [ ] Display boundary fixes

See this file: https://resources.ganderoceanic.com/data/fixes.json

![image](https://user-images.githubusercontent.com/31175571/84329589-6d131f00-abc8-11ea-9c1c-991c388ecdd4.png)

**Comment by lieseldownes24** [comment]
Some of it done: be1cee4d97c020b8eba4f15e85dabc8925967189
