### ISSUE TITLE
Event rostering process

### ISSUE THREAD

**Issue by lieseld** [czqoocavatsim/czqo-core#97]
Tyler suggested to allow for event rosters to be processed on the website itself, similar to [events.vatpac.org](https://cdn.discordapp.com/attachments/762899683748085770/762900327561035776/unknown.png). 

Have controllers apply for timings (probably 30min intervals), show in a graphic, and allow the EC to allocate controllers to timings.

**Comment by cocoiadrop** [comment]
Example of what Tyler has suggested, though we won't take this full UI (I'm not a big fan of it) https://cdn.discordapp.com/attachments/762899683748085770/762900327561035776/unknown.png

> The thing I would want to see if at all possible is the event application/rostering process if it could be applications for times as before but when the roster comes out it could be shown on the website instead of using Google Sheet, it can be shown on the website instead...might take a while to do, I'm happy to use Google sheets till its done but just for future event ease, picture for example

I'll create a controller for this and some models today.

**Comment by JoshuaMicallef** [comment]
Going to be honest. This is a system that is out of my understanding :)

What would you like it to look like? i.e. what parts of that?



*RegardsJoshua Micallef**C3 Controller | I1 Instructor*

**Comment by cocoiadrop** [comment]
I think then I can do a lot of the base stuff and get it "working", and then have you help with refining it and adding simple things to it. I think what Tyler wants is the ability for controllers to select timings on a 30min-1hr period (blocks), and then for him to be able to assign controllers to those blocks for certain positions.

**Comment by andrewogden1678** [comment]
This will be *very* cool for CTP and other events

**Comment by cocoiadrop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Event rostering system](https://trello.com/c/NJmPDVnM/10-event-rostering-system)
