### ISSUE TITLE
Change email template to something prettier/fix dead links in emails

### ISSUE THREAD

**Issue by lieseld** [czqoocavatsim/czqo-core#98]

**Comment by lieseldownes24** [comment]
Not entirely done but progress c385ac204b42475f089b3547e2d599d38bbed2bd

**Comment by viljowilding** [comment]
As discussed, look into the lawful basis for processing for different types of emails and identify the type of processing used (ie consent for specific types of emails, legitimate interests for necessary account emails)

**Comment by cocoiadrop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change email template to something prettier/fix dead links in emails](https://trello.com/c/cCrMtqxG/9-change-email-template-to-something-prettier-fix-dead-links-in-emails)
