### ISSUE TITLE
Custom pages

### ISSUE THREAD

**Issue by lieseld** [czqoocavatsim/czqo-core#99]
Allow for custom pages to be made on the website so we can have things like the euro sounds and vnaaats beta pages editable by staff and such

- Allow the addition of a form (similar to the feedback page)
- Allow limiting it to a specific role
- add more here as I think of them

**Comment by cocoiadrop** [comment]
It is _largely_ done, just need to add permissions c385ac204b42475f089b3547e2d599d38bbed2bd

**Comment by cocoiadrop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Custom pages](https://trello.com/c/2IBphK7b/3-custom-pages)
